### ISSUE TITLE
including lineplot and scatterplot

### ISSUE THREAD

**Issue by josephmarturano** [JuliaPy/Seaborn.jl#12]
Thanks for this excellent package. I like the convenience of Seaborn and use it regularly.

But I do have a question. Is there a reason why the Seaborn functions `lineplot` and `scatterplot` are not included? For example, the following scatterplot code errors:

`using Seaborn; scatterplot(rand(50), rand(50))`

whereas using PyCall works for scatterplots:

`using PyCall; snspy = pyimport("seaborn"); snspy.scatterplot(rand(50), rand(50))`

**Comment by malmaud** [comment]
Only since no one has bothered to add it. Do you want to submit a pull request? If you look at the existing code, I think you'll find it quite easy to see how to add it.

**Comment by josephmarturano** [comment]
Okay, in that case, I submitted a new pull request. My goal was to add lineplot, scatterplot, and relplot.

**Comment by malmaud** [comment]
Closed by https://github.com/JuliaPy/Seaborn.jl/issues/12
