### ISSUE TITLE
despine() function not working

### ISSUE THREAD

**Issue by milanhej** [JuliaPy/Seaborn.jl#14]
Generally I find that Seaborn.jl works smoothly, but came across the

```
sns.despine()
```
function, which doesn't seem to work.  Is there a workaround, apart from using PyCall?
https://seaborn.pydata.org/generated/seaborn.despine.html

Thanks.

**Comment by malmaud** [comment]
A pull request to add that function would be welcome. 

If you look at https://github.com/JuliaPy/Seaborn.jl/blob/master/src/Seaborn.jl, it already has examples you can follow of how to add a new function like `despine`.

**Comment by malmaud** [comment]
Now implemented.
