### ISSUE TITLE
Update for seaborn v0.11.0+ ?

### ISSUE THREAD

**Issue by ShuhuaGao** [JuliaPy/Seaborn.jl#28]
There is a major release in seaborn [v0.11.0](https://seaborn.pydata.org/whatsnew.html#v0-11-0-september-2020) (September 2020) with some API changes and deprecations. Any plan to update `Seaborn.jl` for it? I can try to make a PR in the next few weeks if needed.

**Comment by malmaud** [comment]
PR would be welcome, thanks.
