### ISSUE TITLE
Equivalent to facet_kws=dict(sharex=False)

### ISSUE THREAD

**Issue by egolep** [JuliaPy/Seaborn.jl#29]
I'm using the relplot function and I have to do multiple graphics with different X scales.

In Python, I would use facet_kws=dic(sharex=False), but in Julia I obviously can't do it since the Dict constructor does not have the sharex parameter.
Is there a similar parameter that I'm missing? Or how could I achieve the same result?

**Comment by malmaud** [comment]
In Julia, the syntax for making a dictionary literal is `Dict(:sharex=>false)`.
